# Header
menu:
  主页: /
  生平: /lifetime
  文章: /archives
  相册: /photo
  #图片: /categories/photo
  #相册(需翻墙): /instagram

# SubNav
subnav:
  #github: "#"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: 'UA-62598674-1'
favicon: /favicon.png

#你的头像url
avatar: "/img/xinli.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:


#是否开启“关于我”。
aboutme: 一位父亲、丈夫、教师、同学
